### DISCUSSION TITLE
Official Docker Image

### DISCUSSION THREAD

**Discussion by uhlhosting** [makeplane/plane#2799] [Q&A]
Any plans to release official docker image?

I checked your docker compose now, and is not something we would like to use as it is. Since we work with caprover mainly, a saas heroku self hosted alternative, that uses docker swarm. so anything works there.

yet since we can build our own templates here is example:

```
captainVersion: 4
services:
    # Recipes
    $$cap_appname:
        image: vabene1111/recipes:$$cap_recipes_version
        environment:
            SECRET_KEY: $$cap_app_key
            POSTGRES_HOST: srv-captain--$$cap_appname-db
            POSTGRES_USER: $$cap_db_user
            POSTGRES_DB: $$cap_db_name
            POSTGRES_PASSWORD: $$cap_db_pass
            POSTGRES_PORT: 5432
        volumes:
            - $$cap_appname-staticfiles:/opt/recipes/staticfiles
            - $$cap_appname-mediafiles:/opt/recipes/mediafiles
        caproverExtra:
            containerHttpPort: 8080
    # Postgres
    $$cap_appname-db:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: $$cap_db_user
            POSTGRES_DB: $$cap_db_name
            POSTGRES_PASSWORD: $$cap_db_pass
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        caproverExtra:
            notExposeAsWebApp: 'true'

caproverOneClickApp:
    variables:
        - id: $$cap_recipes_version
          label: Recipes Version
          defaultValue: 1.5.6
          description: Checkout their docker page for the valid tags https://hub.docker.com/r/vabene1111/recipes/tags
        - id: $$cap_app_key
          label: Secret | Key
          description: |-
              Secret key.
              Random secret key, use for example `base64 /dev/urandom | head -c50` to generate one.
          defaultValue: q/UtylBhw5Ars/KXq1UUPeaY80Ai4rshW6ukWg696XFr1+brEm
        - id: $$cap_db_user
          label: Postgres database user
          defaultValue: shynet
          description: Enter a user for database
        - id: $$cap_db_name
          label: Postgres database name
          defaultValue: shynet_db
          description: Enter a databse name
        - id: $$cap_db_pass
          label: Postgres database password
          defaultValue: $$cap_gen_random_hex(24)
          description: Enter database password
    instructions:
        start: >-
            Application for managing recipes, planning meals, building shopping lists and much much more!
        end: >-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: Tandoor Recipes
    isOfficial: true
    description: The recipe manager that allows you to manage your ever growing collection of digital recipes.
    documentation: Taken from https://docs.tandoor.dev/install/docker/#docker.
```

And we have nginx proxy on top of all apps. Also I use aa self hosted instance of Minio, as long as I can define ENV vars to access it, would be enough.

So in my case, I can just use the official plane image if you will release one, and add DB and REDIS. With their values, and done. Deployment in under 30 seconds. And we are live!
