### ISSUE TITLE
[feature]: Discord webhook notifications

### ISSUE THREAD

**Issue by Unyxos** [makeplane/plane#1183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow to receive projects' updates in a Discord server using a webhook integration

### Why should this be worked on?

The idea would be to be able to setup a discord webhook to receive updates from projects in a discord server, similarly to how Gitlab does it when new changes happen in projects : https://docs.gitlab.com/ee/user/project/integrations/discord_notifications.html

It'd be helpful to "track" updates from other team members when using Discord as the team's discussion tool :)

**Comment by Pdzly** [comment]
Documentation to that: https://discord.com/developers/docs/resources/webhook

I could imagine that it could be used as general webhook system. ( That it isnt discord.com.... locked ) But its on the discords format. ( well known everywhere )

**Comment by dongphuchaitrieu** [comment]
Really need webhook to integrate Plane to my system.

**Comment by allen-munsch** [comment]
+1

**Comment by allen-munsch** [comment]
Here's a serverless framework cloudfunction function, haven't tested it yet, but something like this please, like 200 events "free" per month,  and  x amount after per unit cost to run the cloud function, plus whatever your cut would be:

index.js:

```js
'use strict';

const axios = require('axios');


// https://app.plane.so/<your-org>/projects/<project-id>/modules/<item-id>
// {
//   "event": "module",
//   "action": "create",
//   "webhook_id": "xyz",
//   "workspace_id": "blah",
//   "data": {
//     "id": "<item-id>",
//     "created_at": "2024-03-03T18:04:25.779869Z",
//     "updated_at": "2024-03-03T18:04:25.779883Z",
//     "name": "test webhook / module create",
//     "description": "",
//     "description_text": null,
//     "description_html": null,
//     "start_date": null,
//     "target_date": null,
//     "status": "backlog",
//     "view_props": {},
//     "sort_order": 15535,
//     "external_source": null,
//     "external_id": null,
//     "created_by": "<your-user-id>",
//     "updated_by": "<your-user-id>",
//     "project": "<project-id>",
//     "workspace": "blah",
//     "lead": null,
//     "members": []
//   }
// }
// {"event": "issue",
//  "action": "create",
//  "webhook_id": "8e9d69a9-asfasdf",
//  "workspace_id": "2d9949ca-asdfasdf",
//  "data": {
//     "id": "4b8db4d1-efd9-asdfasdf",
//     "cycle": null,
//     "labels": [],
//     "assignees": [],
//     "state": {
//             "id": "asdfasdf",
//             "name": "Cancelled",
//             "color": "#EF4444",
//             "group": "cancelled"
//         },
//     "created_at": "2024-03-03T17:52:12.737498Z",
//     "updated_at": "2024-03-03T17:52:12.737511Z",
//     "estimate_point": null,
//     "name": "test webhook",
//     "description": {},
//     "description_html": "<p></p>",
//     "description_stripped": "",
//     "priority": "none",
//     "start_date": null,
//     "target_date": null,
//     "sequence_id": 13,
//     "sort_order": 65535.0,
//     "completed_at": null,
//     "archived_at": null,
//     "is_draft": false,
//     "external_source": null,
//     "external_id": null,
//     "created_by": "<your-user-id>",
//     "updated_by": "<your-user-id>",
//     "project": "<project-id>",
//     "workspace": "blah",
//     "parent": null
//   }
// }
let ORG_NAME = '<your-org-name>'
const discordWebhookId = process.env['DISCORD_WEBHOOK_ID'] || '';
const discordWebhookToken = process.env['DISCORD_WEBHOOK_ID'] || '';

exports.http = async (request, response) => {
  let {event, action, data} = request.body;
  await sendPlaneEventToDiscord(event, action, data, discordWebhookId, discordWebhookToken);
  response.status(200).send('Hello World!');
};

exports.event = (event, callback) => {
  callback();
};

/**
 * Transforms a Plane.so webhook event to a Discord message format and sends it.
 * 
 * @param {string} planeEvent - The Plane.so webhook event: "issue", "module", "project", ???
 * @param {string} planeAction - The Plane.so webhook event object.
 * @param {object} planeData - The Plane.so webhook event object.
 * @param {string} discordWebhookId - The Discord webhook ID.
 * @param {string} discordWebhookToken - The Discord webhook token.
 */
async function sendPlaneEventToDiscord(planeEvent, planeAction, planeData, discordWebhookId, discordWebhookToken) {
    // Construct the Discord webhook URL
    const webhookUrl = `https://discord.com/api/webhooks/${discordWebhookId}/${discordWebhookToken}`;
    let url = ''
    if (planeEvent == 'issue' || 'module') {
      url = `https://app.plane.so/${ORG_NAME}/projects/${data.project}/${action}s/${data.id}`;
    }
    let PROJECT = 'unknown';
    if (data.project === '<project-id>'){
      PROJECT = 'blah'
    }

    // Transform the Plane.so event to a Discord message format
    const discordMessage = {
        content: `${planeEvent} ${planeAction}`,
        embeds: [{
            title: planeEvent.data.workspace_detail.name,
            description: `Project **${PROJECT}**\n\n**Description:** ${data.description || 'No description provided.'}`,
            color: 3447003, // You can set a color code for the embed
            fields: [
                { name: "Updated At", value: data.updated_at, inline: true },
                { name: "Event ID", value: data.id, inline: true },
                { name: "Url", value: url, inline: true},
                { name: "User ID", value: data.updated_by, inline: true},
            ]
        }],
    };

    try {
        // Make a POST request to the Discord webhook URL
        const response = await axios.post(webhookUrl, discordMessage);
        console.log('Message sent to Discord:', response.data);
    } catch (error) {
        console.error('Error sending message to Discord:', error.response ? error.response.data : error.message);
    }
}
```

package.json:

```
{
  "name": "plane-to-discord-webhook",
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "serverless.com",
  "license": "MIT",
  "devDependencies": {
    "serverless-google-cloudfunctions": "*"
  },
  "dependencies": {
    "axios": "^1.6.7"
  }
}
```

serverless.yml:

```yaml
service: plane-to-discord-webhook

provider:
  name: google
  stage: dev
  runtime: nodejs10
  region: us-central1
  project: <your-google-project-id>
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json

frameworkVersion: '3'

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
  # NOTE: the following uses an "event" event (pubSub event in this case).
  # Please create the corresponding resources in the Google Cloud
  # before deploying this service through Serverless
  #second:
  #  handler: event
  #  events:
  #    - event:
  #        eventType: providers/cloud.pubsub/eventTypes/topic.publish
  #        resource: projects/*/topics/my-topic
# you can define resources, templates etc. the same way you would in a
# Google Cloud deployment configuration
#resources:
#  resources:
#    - type: storage.v1.bucket
#      name: my-serverless-service-bucket
#  imports:
#    - path: my_template.jinja
```


- https://www.serverless.com/framework/docs/providers/google/guide/credentials/
