### ISSUE TITLE
[bug]: grep: apps//.next: No such file or directory

### ISSUE THREAD

**Issue by TheZoker** [makeplane/plane#1958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I updated my plane instance to the latest version (0.11) yesterday and since then my instance is not reachable anymore. 
I use the pre-build docker images within a docker compose file:

```yml
version: '3.8'
services:
  plane-web:
    image: makeplane/plane-frontend
    container_name: planefrontend
    restart: always
    command: /usr/local/bin/start.sh
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_GOOGLE_CLIENTID: 0
      NEXT_PUBLIC_GITHUB_APP_NAME: 0
      NEXT_PUBLIC_GITHUB_ID: 0
      NEXT_PUBLIC_SENTRY_DSN: 0
      NEXT_PUBLIC_ENABLE_OAUTH: 0
      NEXT_PUBLIC_ENABLE_SENTRY: 0
    depends_on:
      - plane-api
      - plane-worker
  plane-api:
    image: makeplane/plane-backend
    container_name: planebackend
    restart: always
    command: ./bin/takeoff
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: plane.settings.production
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}
      REDIS_URL: redis://plane-redis:6379/
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      WEB_URL: ${WEB_URL}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DISABLE_COLLECTSTATIC: 1
      DOCKERIZED: 1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GPT_ENGINE: ${GPT_ENGINE}
      SECRET_KEY: ${SECRET_KEY}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      USE_MINIO: ${USE_MINIO}
    depends_on:
      - plane-db
      - plane-redis
  plane-worker:
    image: makeplane/plane-worker
    container_name: planeworker
    restart: always
    command: ./bin/worker
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: plane.settings.production
      DATABASE_URL: postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}
      REDIS_URL: redis://plane-redis:6379/
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT}
      WEB_URL: ${WEB_URL}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DISABLE_COLLECTSTATIC: 1
      DOCKERIZED: 1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GPT_ENGINE: ${GPT_ENGINE}
      SECRET_KEY: ${SECRET_KEY}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      USE_MINIO: ${USE_MINIO}
    depends_on:
      - plane-api
      - plane-db
      - plane-redis
  plane-db:
    image: postgres:15.2-alpine
    container_name: plane-db
    restart: always
    command: postgres -c 'max_connections=1000'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ~/files/db:/var/lib/postgresql/data
  plane-redis:
    image: redis:6.2.7-alpine
    container_name: plane-redis
    restart: always
    volumes:
      - ~/files/redis:/data
  plane-minio:
    image: minio/minio
    container_name: plane-minio
    restart: always
    volumes:
      - ~/files/minio:/export
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: server /export --console-address ":9090"
  createbuckets:
    image: minio/mc
    env_file:
      - .env
    depends_on:
      - plane-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add plane-minio http://plane-minio:9000 \$AWS_ACCESS_KEY_ID \$AWS_SECRET_ACCESS_KEY;
      /usr/bin/mc mb plane-minio/\$AWS_S3_BUCKET_NAME;
      /usr/bin/mc anonymous set download plane-minio/\$AWS_S3_BUCKET_NAME;
      exit 0;
      "
  plane-proxy:
    image: makeplane/plane-proxy
    container_name: plane-proxy
    restart: always
    ports:
      - ${NGINX_PORT}:80
    env_file:
      - .env
    environment:
      FILE_SIZE_LIMIT: ${FILE_SIZE_LIMIT:-5242880}
      BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-uploads}
    depends_on:
      - plane-web
      - plane-api
```

The only container that is not working is the frontend container. Here is the log of this container:

```
Starting Plane Frontend..
+ /usr/local/bin/replace-env-vars.sh http://localhost:8000 https://projects.gareis.dev
Replacing all statically built instances of http://localhost:8000 with this string https://projects.gareis.dev .
grep: apps//.next: No such file or directory
+ echo 'Starting Plane Frontend..'
+ node
Starting Plane Frontend..
+ /usr/local/bin/replace-env-vars.sh http://localhost:8000 https://projects.gareis.dev
Replacing all statically built instances of http://localhost:8000 with this string https://projects.gareis.dev .
grep: apps//.next: No such file or directory
Starting Plane Frontend..
+ echo 'Starting Plane Frontend..'
+ node
```

And this is the output of a `docker ps` command:
```
f53c05e5edb4   makeplane/plane-proxy      "/docker-entrypoint.…"   20 hours ago   Up 20 hours                    0.0.0.0:80->80/tcp, :::80->80/tcp   plane-proxy
2e7d855ceb83   makeplane/plane-frontend   "docker-entrypoint.s…"   20 hours ago   Restarting (0) 9 seconds ago                                       planefrontend
d143224d65ac   makeplane/plane-worker     "./bin/worker"           20 hours ago   Up 20 hours                    8000/tcp                            planeworker
ac0dc66296b3   makeplane/plane-backend    "./bin/takeoff"          20 hours ago   Up 20 hours                    8000/tcp                            planebackend
4023172a6bfd   minio/minio                "/usr/bin/docker-ent…"   6 days ago     Up 6 days                      9000/tcp                            plane-minio
3c1390385ca6   postgres:15.2-alpine       "docker-entrypoint.s…"   6 days ago     Up 6 days                      5432/tcp                            plane-db
53ac510d5aa7   redis:6.2.7-alpine         "docker-entrypoint.s…"   2 months ago   Up 6 days                      6379/tcp 
```

### Steps to reproduce

1. Setup plane using the docker compose file above
2. Start latest version

### Browser

Google Chrome

### Version

Self-hosted
