### ISSUE TITLE
[bug]: `plane-deploy` manifest unknown error

### ISSUE THREAD

**Issue by TheZoker** [makeplane/plane#2151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I added the new `plane-deploy` package to my docker-compose file, but when I try to pull it, I get the following error:
```
Error response from daemon: manifest for makeplane/plane-deploy:latest not found: manifest unknown: manifest unknown
```

This is the part within my compose file:

```yaml
  plane-deploy:
    image: makeplane/plane-deploy
    container_name: planedeploy
    restart: always
    command: /usr/local/bin/start.sh space/server.js space
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    depends_on:
      - plane-api
      - plane-worker
      - plane-web
```

### Steps to reproduce

1. Add deploy to compose file
2. Start

### Browser

Google Chrome

### Version

Self-hosted

**Comment by hifnStudio** [comment]
```
plane-deploy:
                container_name: planedeploy
                image: makeplane/plane-deploy:latest
                restart: always
                command: /usr/local/bin/start.sh space/server.js space
                env_file:
                        - .env
                environment:
                        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
                depends_on:
                        - plane-api
                        - plane-worker
  ```
  
  Latest image is not available on docker hub. It's still on develop version and we have to run v0.11,
