### ISSUE TITLE
[bug]: Unable to run web and api on separate URLs when self-hosting (due to the removal of the `NEXT_PUBLIC_API_BASE_URL` env variable)

### ISSUE THREAD

**Issue by jordibeen** [makeplane/plane#2434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hey all, I'm wondering why the `NEXT_PUBLIC_API_BASE_URL` environment variables doesn't work anymore on `v0.13.2-dev`? I set both `NEXT_PUBLIC_API_BASE_URL` and `BUILT_NEXT_PUBLIC_API_BASE_URL` to "http://localhost:8000", but the frontend still tries to request `/api/...` on the same host. 

Even though this [code](https://github.com/makeplane/plane/blob/v0.13.2-dev/web/helpers/common.helper.ts) still seems to indicate that it's an environment variable, it looks like [this PR](https://github.com/makeplane/plane/pull/2135) "accomplished" to let the frontend always request to `/api` on the same host. [This page](https://docs.plane.so/self-hosting#environment-variables) also references the removal of this environment variable. I'm not entirely sure why it's being deprecated?

I'm hosting Plane on Kubernetes, and I use the pre-built `makeplane/plane-frontend` & `makeplane/plane-backend` images from Docker Hub. So passing it as a "build argument" isn't possible for me. But I do run web and deploy on different services, so I don't want the web and deploy containers to make requests on the same host!

Please reconsider being able to pass custom web and API URLs.

### Steps to reproduce

Self-host the pre-built `makeplane/plane-frontend` & `makeplane/plane-backend` images from Docker Hub, and run both the web and api on different URLs.

### Browser

Other

### Version

Self-hosted

**Comment by nkigen** [comment]
@jordibeen  I found a workaround: Have the same url for both the client and api server then in the ingress of the api set the path to `/api` and set the priority field to something big. e.g.
```
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $appName }}-service
                port:
                  number: 80
            priority: 100
```
