### ISSUE TITLE
[bug]: DATABASE_URL path error on latest makeplane/plane-backend docker hub

### ISSUE THREAD

**Issue by dkotama** [makeplane/plane#2809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I follow the tutorial on https://docs.plane.so/self-hosting

setting up the .env file on root and run, 

`docker compose -f docker-compose-hub.yml up`

the container api keep returning error :
```
OperationalError: connection failed: FATAL:  database "plane_prod:[pass]@[ip]:22846/plane_prod}" does not exist
```

Surprised by this checked my connection using DB client, and ok,
this is my .env file

```
# Database Settings
PGUSER="postgres"
PGPASSWORD=[pass]
PGHOST=[host]
PGDATABASE="plane_prod"
DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}
```

I tried to build it manually using :
```
services:
  api:
    container_name: api
    build:
      context: ./apiserver
      dockerfile: Dockerfile.api
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    command: ./bin/takeoff
    env_file:
      - .env
```

No error 

**Conclusion**
Seems there was error on the latest official images

### Steps to reproduce

1. clone repo
2. set the postgres env to be remote env
3. run the `docker compose -f docker-compose-hub.yml up` to get the official images

### Browser

Google Chrome

### Version

Self-hosted
