### ISSUE TITLE
[bug]: minio error `Fatal glibc error: CPU does not support x86-64-v2`

### ISSUE THREAD

**Issue by luizvaz** [makeplane/plane#3527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Lots of log lines reporting the below error on Minio:
```
plane-app-plane-minio-1: Fatal glibc error: CPU does not support x86-64-v2
```

### Steps to reproduce

1. Use the ./setup.sh to start the app
2. Run the Docker command to watch the logs
    `docker logs plane-app-plane-minio-1 -f`
3. Check the lines for any errors

**Solution:**
According to Minio issues, the cause is the deprecated CPU.
To solve this, we need to change the version tag cpuv1 instead of lastest:
https://hub.docker.com/r/minio/minio/tags?page=1&name=cpu

https://github.com/minio/minio/issues/18365#issuecomment-1837143798

Change manually the docker-compose.yml from:
```
  plane-minio:
    <<: *app-env
    image: minio/minio
    restart: unless-stopped
    command: server /export --console-address ":9090"
    volumes:
      - uploads:/export
```

To:
```
  plane-minio:
    <<: *app-env
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z-cpuv1
    restart: unless-stopped
    command: server /export --console-address ":9090"
    volumes:
      - uploads:/export
```

### Browser

Google Chrome

### Version

Self-hosted
