### ISSUE TITLE
[bug]: setup.sh not working correctly when deploying self-hosting latest stable version

### ISSUE THREAD

**Issue by dev-un** [makeplane/plane#3557]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When deploying the latest stable version according to the documentation on self-hosting, an error occurs.
The problem is with `setup.sh` and `docker-compose.yaml`. 
When the user selects `action 1 - Install` from `setup.sh`
```
Select an Action you want to perform:
   1) Install
```
He receives an error from docker: `Error response from daemon: manifest for makeplane/plane-proxy:master not found: manifest unknown: manifest unknown`
It is logical that the `master` container does not exist
This is due to the fact that in the script code, the exported `APP_RELEASE` variable inherits the value of the `BRANCH` variable. In this case, `master`. 
```
#!/bin/bash

BRANCH=master
SCRIPT_DIR=$PWD
PLANE_INSTALL_DIR=$PWD/plane-app
export APP_RELEASE=latest
export DOCKERHUB_USER=makeplane
export PULL_POLICY=always
USE_GLOBAL_IMAGES=1
```
When performing the installation action, this script does not change the variable and then runs `docker-compose.yaml`.
`docker-compose.yaml` uses the `APP_RELEASE` variable when deploying containers, which ultimately results in an error, because the `master` containers do not exist
```
services:
  web:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-frontend:${APP_RELEASE:-latest}
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: /usr/local/bin/start.sh web/server.js web
    deploy:
      replicas: ${WEB_REPLICAS:-1}
    depends_on:
      - api
      - worker

```
This error occurs precisely when installing from a script (action 1 from the script)
```
Select an Action you want to perform:
   1) Install
```

### Steps to reproduce

1. Run `setup.sh`
2. Select `1) Install`
3. `Error response from daemon: manifest for makeplane/plane-proxy:master not found: manifest unknown: manifest unknown`

### Browser

Google Chrome

### Version

Self-hosted

**Comment by dev-un** [comment]
I'm sorry, it turns out this problem was also noted in [[bug]: Upgrading via setup.sh had no effect](https://github.com/makeplane/plane/issues/3529#issuecomment-1924732719)
But so far no answer has been received, so I will leave this error unclosed

As a temporary solution for users who encounter this problem, change `docker-compose.yaml` or `setup.sh`

**Via setup.sh**
Replace the value of the `APP_RELEASE` variable with `latest`

**Was**
```
export APP_RELEASE=$BRANCH
```

**Became**
```
export APP_RELEASE=latest
```

**Via docker-compose.yaml**
Throughout the file, replace `${APP_RELEASE:-latest}` with `latest` on all lines. Example:

**Was**
```
beat-worker:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-latest}
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: ./bin/beat
    depends_on:
      - api
      - plane-db
      - plane-redis
```

**Became**
```
beat-worker:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:latest
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: ./bin/beat
    depends_on:
      - api
      - plane-db
      - plane-redis
```

I hope @HiveologieMLData helps you
