### ISSUE TITLE
[bug]: Cannot connect to amqp://guest:**@127.0.0.1:5672/: Connection refused.

### ISSUE THREAD

**Issue by tomerh2001** [makeplane/plane#5776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

> ❗❗ IMPORTANT: When upgrading to v0.23, make sure you are using the latest version of Docker Compose. If you are on a custom Docker setup, you'll need to install RabbitMQ and provide the necessary env variables in app-env.

What are the env variables that I need to define? I can't find a `connection_url` like env variable that specifies how to access rabbitMQ...

### Steps to reproduce

What I added is this:
`compose.yml`:
```
  plane-mq:
    image: rabbitmq:3-management-alpine
    container_name: ${SLUG}-mq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - ${SERVICES_DATASET}/${SLUG}-rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
``` 

`.env`:
```
# RABBITMQ SETTINGS
RABBITMQ_HOST="plane-mq"
RABBITMQ_PORT="5672"
RABBITMQ_USER="plane"
RABBITMQ_PASSWORD="plane"
RABBITMQ_VHOST="plane"
```

But it doesn't work, what am I missing?

### Environment

Production

### Browser

None

### Variant

Self-hosted

### Version

0.23
