### ISSUE TITLE
[bug]: The community edition shows error when trying to access the system

### ISSUE THREAD

**Issue by arnabJ** [makeplane/plane#7003]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Introduction
I have created my own `docker-compose.yml` by referencing the docker-compose.yaml that gets downloaded when we select `install` after running `setup.sh` All the services have started and the logs are clean too. When I visit the `domain` I have mentioned in `WEB_URL` env variable, I see:
```
Plane didn't start up. This could be because one or more Plane services failed to start.
Choose View Logs from setup.sh and Docker logs to be sure.
```

I am using custom DB, Redis, MinIO, RabbitMQ & Proxy.
I have added reverse proxy for MinIO and enabled SSL. I am using the https://minio.domain.com as the value in .env for `AWS_S3_ENDPOINT_URL`.

[plane-worker-20250501183223.log](https://github.com/user-attachments/files/20000013/plane-worker-20250501183223.log)
[plane-web-20250501183209.log](https://github.com/user-attachments/files/20000019/plane-web-20250501183209.log)
[plane-space-20250501183204.log](https://github.com/user-attachments/files/20000012/plane-space-20250501183204.log)
[plane-migrator-20250501183236.log](https://github.com/user-attachments/files/20000015/plane-migrator-20250501183236.log)
[plane-beat-worker-20250501183218.log](https://github.com/user-attachments/files/20000014/plane-beat-worker-20250501183218.log)
[plane-admin-20250501183152.log](https://github.com/user-attachments/files/20000018/plane-admin-20250501183152.log)
[plane-api-20250501183229.log](https://github.com/user-attachments/files/20000017/plane-api-20250501183229.log)
[plane-live-20250501183159.log](https://github.com/user-attachments/files/20000016/plane-live-20250501183159.log)

I have uploaded all the 8 log files and my docker-compose.yml is added below:

### docker-compose.yml
```yaml
services:
    plane-api:
        image: artifacts.plane.so/makeplane/plane-backend:${APP_VERSION:-stable}
        container_name: plane-api
        command: ./bin/docker-entrypoint-api.sh
        restart: unless-stopped
        volumes:
            - ./api/logs:/code/plane/logs
        networks:
            - my-network
        environment:
            - WEB_URL
            - DEBUG
            - CORS_ALLOWED_ORIGINS
            - GUNICORN_WORKERS
            - USE_MINIO
            - DATABASE_URL
            - REDIS_URL
            - SECRET_KEY
            - AMQP_URL
            - API_KEY_RATE_LIMIT
            - MINIO_ENDPOINT_SSL
            - AWS_REGION
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_S3_ENDPOINT_URL
            - AWS_S3_BUCKET_NAME

    plane-worker:
        image: artifacts.plane.so/makeplane/plane-backend:${APP_RELEASE:-stable}
        container_name: plane-worker
        command: ./bin/docker-entrypoint-worker.sh
        restart: unless-stopped
        volumes:
            - ./worker/logs:/code/plane/logs
        networks:
            - my-network
        environment:
            - WEB_URL
            - DEBUG
            - CORS_ALLOWED_ORIGINS
            - GUNICORN_WORKERS
            - USE_MINIO
            - DATABASE_URL
            - REDIS_URL
            - SECRET_KEY
            - AMQP_URL
            - API_KEY_RATE_LIMIT
            - MINIO_ENDPOINT_SSL
            - AWS_REGION
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_S3_ENDPOINT_URL
            - AWS_S3_BUCKET_NAME
        depends_on:
            - plane-api

    plane-web:
        image: artifacts.plane.so/makeplane/plane-frontend:${APP_RELEASE:-stable}
        container_name: plane-web
        command: node web/server.js web
        restart: unless-stopped
        networks:
            - my-network
        ports:
            - 9004:3000
        depends_on:
            - plane-api
            - plane-worker

    plane-space:
        image: artifacts.plane.so/makeplane/plane-space:${APP_RELEASE:-stable}
        container_name: plane-space
        command: node space/server.js space
        restart: unless-stopped
        networks:
            - my-network
        depends_on:
            - plane-api
            - plane-worker
            - plane-web

    plane-admin:
        image: artifacts.plane.so/makeplane/plane-admin:${APP_RELEASE:-stable}
        container_name: plane-admin
        command: node admin/server.js admin
        restart: unless-stopped
        networks:
            - my-network
        depends_on:
            - plane-api
            - plane-web

    plane-live:
        image: artifacts.plane.so/makeplane/plane-live:${APP_RELEASE:-stable}
        container_name: plane-live
        command: node live/dist/server.js live
        restart: unless-stopped
        networks:
            - my-network
        environment:
            - API_BASE_URL
        depends_on:
            - plane-api
            - plane-web

    plane-beat-worker:
        image: artifacts.plane.so/makeplane/plane-backend:${APP_VERSION:-stable}
        container_name: plane-beat-worker
        command: ./bin/docker-entrypoint-beat.sh
        restart: unless-stopped
        volumes:
            - ./beat-worker/logs:/code/plane/logs
        networks:
            - my-network
        environment:
            - WEB_URL
            - DEBUG
            - CORS_ALLOWED_ORIGINS
            - GUNICORN_WORKERS
            - USE_MINIO
            - DATABASE_URL
            - REDIS_URL
            - SECRET_KEY
            - AMQP_URL
            - API_KEY_RATE_LIMIT
            - MINIO_ENDPOINT_SSL
            - AWS_REGION
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_S3_ENDPOINT_URL
            - AWS_S3_BUCKET_NAME
        depends_on:
            - plane-api

    plane-migrator:
        image: artifacts.plane.so/makeplane/plane-backend:${APP_VERSION:-stable}
        container_name: plane-migrator
        command: ./bin/docker-entrypoint-migrator.sh
        restart: unless-stopped
        volumes:
            - ./migrator/logs:/code/plane/logs
        networks:
            - my-network
        environment:
            - WEB_URL
            - DEBUG
            - CORS_ALLOWED_ORIGINS
            - GUNICORN_WORKERS
            - USE_MINIO
            - DATABASE_URL
            - REDIS_URL
            - SECRET_KEY
            - AMQP_URL
            - API_KEY_RATE_LIMIT
            - MINIO_ENDPOINT_SSL
            - AWS_REGION
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_S3_ENDPOINT_URL
            - AWS_S3_BUCKET_NAME

networks:
    my-network:
        external: true
```

### Steps to reproduce

Manually create a custom docker-compose.yml on your own.
Run:
```bash
sudo docker compose up -d
```

All the services will start properly but the website won't be accessible.

### Environment

Production

### Browser

None

### Variant

Self-hosted

### Version

v0.26.0
